### ISSUE TITLE
RSSフィードのリンクを絶対パスに

### ISSUE THREAD

**Issue by gemmaro** [KeenS/KeenS.github.io#7]
https://keens.github.io/ 以下で購読できる各 RSS フィード中のリンクが相対パスになっています．これを絶対パスにしていただけないでしょうか．

# 経緯

Thunderbird のフィード機能で貴誌を購読しようとしたところ，W3C の Feed Validation Service によるエラーが表示されました．

![1611642899971YwTwlO7Im7](https://user-images.githubusercontent.com/29575029/105829850-34fe0680-6008-11eb-9be1-60ae2d3c107b.png)

[表示されているW3Cのページ](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkeens.github.io%2Findex.xml)

# 問題

[`index.xml`](https://github.com/KeenS/KeenS.github.io/blob/master/index.xml) とその他の分類別の各フィードについて，含まれるリンクが相対パスになっています．これは妥当な RSS ではありません．

# 模索

[`config.yaml`](https://github.com/KeenS/KeenS.github.io/blob/source/config.yaml) の `BaseURL` の値を `https://keens.github.io/` に変更することで，各フィードに含まれるリンクが絶対パスになります．しかし， `BaseURL` は記事間のリンク（例えばトップページから各記事へのリンク）にも影響するため，ローカルでの編集の妨げとなることが予想されます．
従って，編集時は `BaseURL` の値は現在のまま変更せず，GitHub Pages に公開する段階でのみ `BaseURL` の値を変更すると良いのではないかと考えました．

# 関連

* https://github.com/gohugoio/hugo/issues/7272

**Comment by KeenS** [comment]
報告ありがとうございます。今のBaseURLが `"/"` になっているのはGitHub PagesがHTTPとHTTPS両方出していた時代にどちらでも動くようにしたものです。現在はenforce HTTPSのオプションがあるのでパスではなくURLを使っても問題ないはずです。ちょっと試してみます。

因みにローカルでの編集時はHugo側でローカルホストをルートにしてくれるので差し障りはなかったはずです。

**Comment by KeenS** [comment]
done

![image](https://user-images.githubusercontent.com/4434568/105919549-31569800-6079-11eb-9d3b-213dbd9fa1e9.png)

**Comment by gemmaro** [comment]
迅速な御対応をいただきありがとうございます．おかげさまで問題なく購読することができました．
