### ISSUE TITLE
og:urlやog:imageに指定されているURLがおかしい

### ISSUE THREAD

**Issue by unarist** [KeenS/KeenS.github.io#8]
例えば https://keens.github.io/blog/2021/01/04/future_of_proguramming_languages/ で見ると、以下のようになっていました。

`og:url` → https:// が二重になっている

```
<meta property="og:url" content="https://https://KeenS.github.io/blog/2021/01/04/future_of_proguramming_languages/" />
```

`og:image` `twitter:image` → origin部が二重になっている

```
<meta property="og:image" content="https://KeenS.github.iohttps://KeenS.github.io/images/ogp/post/future_of_proguramming_languages.png" />
<meta name="twitter:image" content="https://KeenS.github.iohttps://KeenS.github.io/images/ogp/post/future_of_proguramming_languages.png" />
```

**Comment by KeenS** [comment]
報告ありがとうございます。 #7 で雑に変更した影響みたいですね。修正します。

**Comment by KeenS** [comment]
直しました

![image](https://user-images.githubusercontent.com/4434568/105968140-0b0d1880-60ca-11eb-82a9-b41b16d2e2d6.png)
